.TH "Button" 3 "Thu Nov 1 2012" "OpenGui" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Button \- 
.PP
The class used to store buttons consisting of a background image and a foreground text\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Button\&.h>\fP
.PP
Inherits \fBElement\fP\&.
.PP
Inherited by \fBToggleButton\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBButton\fP ()"
.br
.RI "\fIDefault constructor\&. \fP"
.ti -1c
.RI "\fBButton\fP (unsigned int x, unsigned int y)"
.br
.RI "\fIConstructor\&. Sets x and y position of this element\&. \fP"
.ti -1c
.RI "\fBButton\fP (unsigned int x, unsigned int y, unsigned int width, unsigned int height)"
.br
.RI "\fIConstructor\&. Sets x and y position of element along with height and width\&. \fP"
.ti -1c
.RI "\fBButton\fP (unsigned int x, unsigned int y, unsigned int width, unsigned int height, string txt)"
.br
.RI "\fIConstructor\&. Sets x and y position of element along with height, width, and text\&. \fP"
.ti -1c
.RI "\fBButton\fP (unsigned int x, unsigned int y, unsigned int width, unsigned int height, \fBImageElement\fP *img)"
.br
.RI "\fIConstructor\&. Sets x and y position of element along width height\&. Uses an ImageElment as the background image\&. \fP"
.ti -1c
.RI "void \fBsetBgIg\fP (\fBImageElement\fP *img)"
.br
.RI "\fISets background image\&. \fP"
.ti -1c
.RI "void \fBsetText\fP (string txt)"
.br
.RI "\fISets text\&. \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBTextElement\fP * \fB_textE\fP"
.br
.ti -1c
.RI "\fBImageElement\fP * \fB_imageE\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The class used to store buttons consisting of a background image and a foreground text\&. 
.PP
Definition at line 17 of file Button\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Button::Button ()"

.PP
Default constructor\&. 
.SS "Button::Button (unsigned intx, unsigned inty)"

.PP
Constructor\&. Sets x and y position of this element\&. 
.SS "Button::Button (unsigned intx, unsigned inty, unsigned intwidth, unsigned intheight)"

.PP
Constructor\&. Sets x and y position of element along with height and width\&. 
.SS "Button::Button (unsigned intx, unsigned inty, unsigned intwidth, unsigned intheight, stringtxt)"

.PP
Constructor\&. Sets x and y position of element along with height, width, and text\&. 
.SS "Button::Button (unsigned intx, unsigned inty, unsigned intwidth, unsigned intheight, \fBImageElement\fP *img)"

.PP
Constructor\&. Sets x and y position of element along width height\&. Uses an ImageElment as the background image\&. 
.SH "Member Function Documentation"
.PP 
.SS "void Button::setBgIg (\fBImageElement\fP *img)"

.PP
Sets background image\&. 
.SS "void Button::setText (stringtxt)"

.PP
Sets text\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBImageElement\fP* Button::_imageE\fC [protected]\fP"

.PP
Definition at line 29 of file Button\&.h\&.
.SS "\fBTextElement\fP* Button::_textE\fC [protected]\fP"

.PP
Definition at line 28 of file Button\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGui from the source code\&.
