.TH "CheckBox" 3 "Thu Nov 1 2012" "OpenGui" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CheckBox \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CheckBox\&.h>\fP
.PP
Inherits \fBElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCheckBox\fP ()"
.br
.ti -1c
.RI "\fBCheckBox\fP (unsigned int x, unsigned int y)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 12 of file CheckBox\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CheckBox::CheckBox ()\fC [inline]\fP"

.PP
Definition at line 14 of file CheckBox\&.h\&.
.SS "CheckBox::CheckBox (unsigned intx, unsigned inty)\fC [inline]\fP"

.PP
Definition at line 15 of file CheckBox\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGui from the source code\&.
