.TH "element/Element.cpp" 3 "Thu Nov 1 2012" "OpenGui" \" -*- nroff -*-
.ad l
.nh
.SH NAME
element/Element.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Element\&.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include '\&.\&./image/Image\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGui from the source code\&.
