.TH "element/Element.h" 3 "Thu Nov 1 2012" "OpenGui" \" -*- nroff -*-
.ad l
.nh
.SH NAME
element/Element.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include '\&.\&./image/Image\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBElement\fP"
.br
.RI "\fIThe base class that all GUI elements derive from\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This file contains the \fBElement\fP class\&. 
.PP
Definition in file \fBElement\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGui from the source code\&.
