.TH "ImageElement" 3 "Thu Nov 1 2012" "OpenGui" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImageElement \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ImageElement\&.h>\fP
.PP
Inherits \fBElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImageElement\fP ()"
.br
.ti -1c
.RI "\fBImageElement\fP (\fBImage\fP &img)"
.br
.ti -1c
.RI "\fBImageElement\fP (unsigned int x, unsigned int y)"
.br
.ti -1c
.RI "\fBImageElement\fP (unsigned int x, unsigned int y, unsigned int width, unsigned int height)"
.br
.ti -1c
.RI "\fBImageElement\fP (unsigned int x, unsigned int y, unsigned int width, unsigned int height, \fBImage\fP &img)"
.br
.ti -1c
.RI "void \fBclearResult\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 9 of file ImageElement\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImageElement::ImageElement ()\fC [inline]\fP"

.PP
Definition at line 12 of file ImageElement\&.h\&.
.SS "ImageElement::ImageElement (\fBImage\fP &img)\fC [inline]\fP"

.PP
Definition at line 13 of file ImageElement\&.h\&.
.SS "ImageElement::ImageElement (unsigned intx, unsigned inty)\fC [inline]\fP"

.PP
Definition at line 14 of file ImageElement\&.h\&.
.SS "ImageElement::ImageElement (unsigned intx, unsigned inty, unsigned intwidth, unsigned intheight)\fC [inline]\fP"

.PP
Definition at line 17 of file ImageElement\&.h\&.
.SS "ImageElement::ImageElement (unsigned intx, unsigned inty, unsigned intwidth, unsigned intheight, \fBImage\fP &img)\fC [inline]\fP"

.PP
Definition at line 19 of file ImageElement\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void ImageElement::clearResult ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBElement\fP\&.
.PP
Definition at line 22 of file ImageElement\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGui from the source code\&.
