.TH "Image" 3 "Thu Nov 1 2012" "OpenGui" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Image \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Image\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImage\fP ()"
.br
.ti -1c
.RI "\fBImage\fP (unsigned int \fBwidth\fP, unsigned int \fBheight\fP)"
.br
.ti -1c
.RI "\fBImage\fP (unsigned int \fBwidth\fP, unsigned int \fBheight\fP, const \fBPixel\fP &p)"
.br
.ti -1c
.RI "\fBImage\fP (unsigned int \fBwidth\fP, unsigned int \fBheight\fP, unsigned char *data)"
.br
.ti -1c
.RI "\fBImage\fP (\fBImage\fP &img)"
.br
.ti -1c
.RI "\fB~Image\fP ()"
.br
.ti -1c
.RI "unsigned int \fBwidth\fP () const "
.br
.ti -1c
.RI "unsigned int \fBheight\fP () const "
.br
.ti -1c
.RI "void \fBset\fP (unsigned int x, unsigned int y, const \fBPixel\fP &color)"
.br
.ti -1c
.RI "void \fBset\fP (unsigned int x, unsigned int y, unsigned int \fBwidth\fP, unsigned int \fBheight\fP, const \fBPixel\fP &color)"
.br
.ti -1c
.RI "const \fBPixel\fP & \fBget\fP (unsigned int x, unsigned int y) const "
.br
.ti -1c
.RI "\fBPixel\fP * \fBgetPixels\fP ()"
.br
.ti -1c
.RI "void \fBblit\fP (\fBImage\fP &dest, unsigned int xSource, unsigned int ySource, unsigned int xDest, unsigned int yDest, unsigned int \fBwidth\fP, unsigned int \fBheight\fP) const "
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &out, const \fBImage\fP &img)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file Image\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Image::Image ()"

.PP
Definition at line 8 of file Image\&.cpp\&.
.SS "Image::Image (unsigned intwidth, unsigned intheight)"

.PP
Definition at line 14 of file Image\&.cpp\&.
.SS "Image::Image (unsigned intwidth, unsigned intheight, const \fBPixel\fP &p)"

.PP
Definition at line 22 of file Image\&.cpp\&.
.SS "Image::Image (unsigned intwidth, unsigned intheight, unsigned char *data)"

.PP
Definition at line 41 of file Image\&.cpp\&.
.SS "Image::Image (\fBImage\fP &img)"

.PP
Definition at line 31 of file Image\&.cpp\&.
.SS "Image::~Image ()"

.PP
Definition at line 54 of file Image\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void Image::blit (\fBImage\fP &dest, unsigned intxSource, unsigned intySource, unsigned intxDest, unsigned intyDest, unsigned intwidth, unsigned intheight) const"

.PP
Definition at line 115 of file Image\&.cpp\&.
.SS "const \fBPixel\fP & Image::get (unsigned intx, unsigned inty) const"

.PP
Definition at line 102 of file Image\&.cpp\&.
.SS "\fBPixel\fP* Image::getPixels ()\fC [inline]\fP"

.PP
Definition at line 22 of file Image\&.h\&.
.SS "unsigned int Image::height () const"

.PP
Definition at line 63 of file Image\&.cpp\&.
.SS "void Image::set (unsigned intx, unsigned inty, const \fBPixel\fP &color)"

.PP
Definition at line 66 of file Image\&.cpp\&.
.SS "void Image::set (unsigned intx, unsigned inty, unsigned intwidth, unsigned intheight, const \fBPixel\fP &color)"

.PP
Definition at line 80 of file Image\&.cpp\&.
.SS "unsigned int Image::width () const"

.PP
Definition at line 60 of file Image\&.cpp\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "std::ostream& operator<< (std::ostream &out, const \fBImage\fP &img)\fC [friend]\fP"

.PP
Definition at line 147 of file Image\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGui from the source code\&.
