.TH "Pixel" 3 "Thu Nov 1 2012" "OpenGui" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pixel \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Pixel\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPixel\fP ()"
.br
.ti -1c
.RI "\fBPixel\fP (int R, int G, int B)"
.br
.ti -1c
.RI "\fBPixel\fP (int R, int G, int B, int A)"
.br
.ti -1c
.RI "\fBPixel\fP (\fBPixel\fP &p)"
.br
.ti -1c
.RI "void \fBsetRGB\fP (int R, int G, int B)"
.br
.ti -1c
.RI "void \fBsetRGBA\fP (int R, int G, int B, int A)"
.br
.ti -1c
.RI "int \fBgetR\fP () const "
.br
.ti -1c
.RI "int \fBgetG\fP () const "
.br
.ti -1c
.RI "int \fBgetB\fP () const "
.br
.ti -1c
.RI "int \fBgetA\fP () const "
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &out, const \fBPixel\fP &p)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file Pixel\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Pixel::Pixel ()"

.PP
Definition at line 3 of file Pixel\&.cpp\&.
.SS "Pixel::Pixel (intR, intG, intB)"

.PP
Definition at line 4 of file Pixel\&.cpp\&.
.SS "Pixel::Pixel (intR, intG, intB, intA)"

.PP
Definition at line 7 of file Pixel\&.cpp\&.
.SS "Pixel::Pixel (\fBPixel\fP &p)"

.PP
Definition at line 11 of file Pixel\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "int Pixel::getA () const"

.PP
Definition at line 34 of file Pixel\&.cpp\&.
.SS "int Pixel::getB () const"

.PP
Definition at line 31 of file Pixel\&.cpp\&.
.SS "int Pixel::getG () const"

.PP
Definition at line 28 of file Pixel\&.cpp\&.
.SS "int Pixel::getR () const"

.PP
Definition at line 25 of file Pixel\&.cpp\&.
.SS "void Pixel::setRGB (intR, intG, intB)"

.PP
Definition at line 19 of file Pixel\&.cpp\&.
.SS "void Pixel::setRGBA (intR, intG, intB, intA)"

.PP
Definition at line 22 of file Pixel\&.cpp\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "std::ostream& operator<< (std::ostream &out, const \fBPixel\fP &p)\fC [friend]\fP"

.PP
Definition at line 37 of file Pixel\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGui from the source code\&.
