.TH "TextElement" 3 "Thu Nov 1 2012" "OpenGui" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TextElement \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TextElement\&.h>\fP
.PP
Inherits \fBElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextElement\fP (unsigned int x, unsigned int y)"
.br
.ti -1c
.RI "\fBTextElement\fP (unsigned int x, unsigned int y, unsigned int width, unsigned int height)"
.br
.ti -1c
.RI "\fBTextElement\fP (unsigned int x, unsigned int y, unsigned int width, unsigned int height, int size, string txt)"
.br
.ti -1c
.RI "\fB~TextElement\fP ()"
.br
.ti -1c
.RI "void \fBsetText\fP (string txt)"
.br
.ti -1c
.RI "void \fBclearResult\fP ()"
.br
.RI "\fIClears the result image to a color (black is default)\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 9 of file TextElement\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TextElement::TextElement (unsigned intx, unsigned inty)"

.PP
Definition at line 10 of file TextElement\&.cpp\&.
.SS "TextElement::TextElement (unsigned intx, unsigned inty, unsigned intwidth, unsigned intheight)"

.PP
Definition at line 15 of file TextElement\&.cpp\&.
.SS "TextElement::TextElement (unsigned intx, unsigned inty, unsigned intwidth, unsigned intheight, intsize, stringtxt)"

.PP
Definition at line 20 of file TextElement\&.cpp\&.
.SS "TextElement::~TextElement ()"

.PP
Definition at line 28 of file TextElement\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void TextElement::clearResult ()\fC [virtual]\fP"

.PP
Clears the result image to a color (black is default)\&. Renders the background of the element, namely element contents\&. For generic Elements, it blits a solid color (black) image to the element's result image\&. For content elements (\fBTextElement\fP and \fBImageElement\fP) it will blit the stored image (for image elements) or resulting image from rendering the text (for text elements) before rendering the children\&. 
.PP
Reimplemented from \fBElement\fP\&.
.PP
Definition at line 40 of file TextElement\&.cpp\&.
.SS "void TextElement::setText (stringtxt)"

.PP
Definition at line 35 of file TextElement\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGui from the source code\&.
