.TH "text/Text.cpp" 3 "Thu Nov 1 2012" "OpenGui" \" -*- nroff -*-
.ad l
.nh
.SH NAME
text/Text.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Text\&.h'\fP
.br
\fC#include <string>\fP
.br
\fC#include <ft2build\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include '\&.\&./image/Image\&.h'\fP
.br
\fC#include '\&.\&./image/Pixel\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "string \fBgetText\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "string getText ()"
Return string of text stored 
.PP
Definition at line 71 of file Text\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGui from the source code\&.
