.TH "TextElement" 3 "Thu Nov 1 2012" "OpenGui" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TextElement \- 
.PP
The class used to store elements of text\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TextElement\&.h>\fP
.PP
Inherits \fBElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextElement\fP (unsigned int x, unsigned int y)"
.br
.RI "\fIConstructor\&. Sets x and y position of element\&. \fP"
.ti -1c
.RI "\fBTextElement\fP (unsigned int x, unsigned int y, unsigned int width, unsigned int height)"
.br
.RI "\fIConstructor\&. Sets x and y position of element along with height and width\&. \fP"
.ti -1c
.RI "\fBTextElement\fP (unsigned int x, unsigned int y, unsigned int width, unsigned int height, int size, string txt)"
.br
.RI "\fIConstructor\&. Sets x and y position of element along with height, width, font size and content\&. \fP"
.ti -1c
.RI "\fB~TextElement\fP ()"
.br
.RI "\fIDestructor\&. \fP"
.ti -1c
.RI "void \fBsetText\fP (string txt)"
.br
.RI "\fIUpdates the text stored and re-renders the result\&. \fP"
.ti -1c
.RI "void \fBclearResult\fP ()"
.br
.RI "\fIClears the rendered image previously stored\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The class used to store elements of text\&. 
.PP
Definition at line 13 of file TextElement\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TextElement::TextElement (unsigned intx, unsigned inty)"

.PP
Constructor\&. Sets x and y position of element\&. Constructor with just x,y position sets sizes to zero and font size to 1 and uses an empty string 
.PP
Definition at line 10 of file TextElement\&.cpp\&.
.SS "TextElement::TextElement (unsigned intx, unsigned inty, unsigned intwidth, unsigned intheight)"

.PP
Constructor\&. Sets x and y position of element along with height and width\&. Constructor with x,y position, width and height sets font size to 1 and an empty string 
.PP
Definition at line 15 of file TextElement\&.cpp\&.
.SS "TextElement::TextElement (unsigned intx, unsigned inty, unsigned intwidth, unsigned intheight, intsize, stringtxt)"

.PP
Constructor\&. Sets x and y position of element along with height, width, font size and content\&. Constructor sets all variables and dynamically creates a \fBText\fP object 
.PP
Definition at line 20 of file TextElement\&.cpp\&.
.SS "TextElement::~TextElement ()"

.PP
Destructor\&. Destructor deletes dynamically allocated variables if needed 
.PP
Definition at line 27 of file TextElement\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void TextElement::clearResult ()\fC [virtual]\fP"

.PP
Clears the rendered image previously stored\&. Clears the rendered image we have stored 
.PP
Reimplemented from \fBElement\fP\&.
.PP
Definition at line 39 of file TextElement\&.cpp\&.
.SS "void TextElement::setText (stringtxt)"

.PP
Updates the text stored and re-renders the result\&. Updates the value of the text which renders the text 
.PP
Definition at line 34 of file TextElement\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGui from the source code\&.
