.TH "Text" 3 "Thu Nov 1 2012" "OpenGui" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Text \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Text\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBText\fP ()"
.br
.ti -1c
.RI "\fBText\fP (\fBText\fP &txt)"
.br
.ti -1c
.RI "\fBText\fP (int w, int h, int size)"
.br
.ti -1c
.RI "\fBText\fP (int w, int h, int size, string c)"
.br
.ti -1c
.RI "\fB~Text\fP ()"
.br
.ti -1c
.RI "void \fBsetText\fP (string c)"
.br
.ti -1c
.RI "\fBImage\fP * \fBgetImage\fP ()"
.br
.ti -1c
.RI "string \fBgetText\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file Text\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Text::Text ()"

.PP
Definition at line 14 of file Text\&.cpp\&.
.SS "Text::Text (\fBText\fP &txt)"

.PP
Definition at line 41 of file Text\&.cpp\&.
.SS "Text::Text (intw, inth, intsize)"

.PP
Definition at line 19 of file Text\&.cpp\&.
.SS "Text::Text (intw, inth, intsize, stringc)"

.PP
Definition at line 24 of file Text\&.cpp\&.
.SS "Text::~Text ()"

.PP
Definition at line 46 of file Text\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBImage\fP * Text::getImage ()"

.PP
Definition at line 62 of file Text\&.cpp\&.
.SS "string Text::getText (void)\fC [inline]\fP"

.PP
Definition at line 22 of file Text\&.h\&.
.SS "void Text::setText (stringc)"

.PP
Definition at line 56 of file Text\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGui from the source code\&.
