.TH "text/TextElement.cpp" 3 "Thu Nov 1 2012" "OpenGui" \" -*- nroff -*-
.ad l
.nh
.SH NAME
text/TextElement.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include 'Text\&.h'\fP
.br
\fC#include 'TextElement\&.h'\fP
.br
\fC#include '\&.\&./image/Image\&.h'\fP
.br
\fC#include '\&.\&./element/Element\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGui from the source code\&.
