.TH "text/Text.cpp" 3 "Thu Nov 1 2012" "OpenGui" \" -*- nroff -*-
.ad l
.nh
.SH NAME
text/Text.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Text\&.h'\fP
.br
\fC#include <string>\fP
.br
\fC#include <ft2build\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include '\&.\&./image/Image\&.h'\fP
.br
\fC#include '\&.\&./image/Pixel\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGui from the source code\&.
