.TH "ToggleButton" 3 "Thu Nov 1 2012" "OpenGui" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ToggleButton \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ToggleButton\&.h>\fP
.PP
Inherits \fBButton\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBToggleButton\fP ()"
.br
.ti -1c
.RI "\fBToggleButton\fP (int x, int y)"
.br
.ti -1c
.RI "\fBToggleButton\fP (int x, int y, int w, int h)"
.br
.ti -1c
.RI "\fBToggleButton\fP (int x, int y, int w, int h, string txt)"
.br
.ti -1c
.RI "\fBToggleButton\fP (int x, int y, int w, int h, string content, int size, \fBImageElement\fP *i)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 12 of file ToggleButton\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ToggleButton::ToggleButton ()\fC [inline]\fP"

.PP
Definition at line 14 of file ToggleButton\&.h\&.
.SS "ToggleButton::ToggleButton (intx, inty)\fC [inline]\fP"

.PP
Definition at line 15 of file ToggleButton\&.h\&.
.SS "ToggleButton::ToggleButton (intx, inty, intw, inth)\fC [inline]\fP"

.PP
Definition at line 16 of file ToggleButton\&.h\&.
.SS "ToggleButton::ToggleButton (intx, inty, intw, inth, stringtxt)\fC [inline]\fP"

.PP
Definition at line 19 of file ToggleButton\&.h\&.
.SS "ToggleButton::ToggleButton (intx, inty, intw, inth, stringcontent, intsize, \fBImageElement\fP *i)\fC [inline]\fP"

.PP
Definition at line 23 of file ToggleButton\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGui from the source code\&.
